[package]
name = "anoti-platform-linux"
description = "Linux native desktop notification backend for anoti"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anoti-core.workspace = true
anoti-platform.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
zbus = { version = "4.4", default-features = false, features = ["async-io", "blocking"] }
wait-timeout = "0.2"

[lints]
workspace = true
